// <auto-generated />
namespace SqzEvent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201612091451 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201612091451));
        
        string IMigrationMetadata.Id
        {
            get { return "201612090651410_201612091451"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
