// <auto-generated />
namespace SqzEvent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201704241807 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201704241807));
        
        string IMigrationMetadata.Id
        {
            get { return "201704241007482_201704241807"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
