// <auto-generated />
namespace SqzEvent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201703161742 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201703161742));
        
        string IMigrationMetadata.Id
        {
            get { return "201703160942267_201703161742"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
